### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by arvl130** [arvl130/expense-tracker-infra#1]
- [x] add Lambda function for cache invalidation
- [x] automatically create the CDN
- [x] automatically create the S3 bucket
- [ ] ...
